name: Auto release
on: 
  push:

jobs:
  build:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_generic
          # - arc_arc700
          # - arc_archs
          - arm_arm1176jzf-s_vfp
          - arm_arm926ej-s
          - arm_cortex-a15_neon-vfpv4
          - arm_cortex-a5_vfpv4
          - arm_cortex-a7
          - arm_cortex-a7_neon-vfpv4
          - arm_cortex-a8_vfpv3
          - arm_cortex-a9
          - arm_cortex-a9_neon
          - arm_cortex-a9_vfpv3-d16
          - arm_fa526
          - arm_mpcore
          - arm_xscale
          - i386_pentium-mmx
          - i386_pentium4
          - mips64_octeonplus
          - mips_24kc
          - mips_4kec
          - mips_mips32
          - mipsel_24kc
          - mipsel_24kc_24kf
          - mipsel_74kc
          - mipsel_mips32
          - powerpc_464fp
          - powerpc_8540
          - x86_64
          
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Build
        uses: openwrt/gh-action-sdk@v3
        env:
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          ARCH: ${{ matrix.arch }}
          V: sc

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/action/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with: 
          path: artifacts/
      
      - name: Release
        run: |
          time="${{ github.event.head_commit.timestamp }}"
          sha="${GITHUB_SHA:0:8}"
          tag="ci-$(date +'%Y%m%d-%H%M' -d "$time")"
          message="Auto-Release $(date +'%Y-%m-%d %H:%M' -d "$time")"
          hub release create $(for a in artifacts/*/*.ipk; do echo -a $a; done) -t "$GITHUB_SHA" "$tag" -m "$message"
        env:
          GITHUB_TOKEN: ${{ github.token }}

  gh-pages:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pages
        uses: actions/checkout@v2
        with:
          path: 'gh-pages'
          ref: 'pages'

      - name: Backup pages
        run: |
          cp -ar gh-pages pages

      - name: Prepare gh-pages
        run: |
          cd gh-pages
          git checkout --orphan gh-pages
          git rm -rf .

          git config --global user.name bot
          git config --global user.email bot@example.com
    
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with: 
          path: gh-pages/

      - name: Update
        run: |
          cd gh-pages

          echo "::group::Add artifacts"
          git add .
          git commit -m "Add: artifacts"
          echo "::endgroup::"

          echo "::group::Add pages"
          cp -avr ../pages/* ./
          git add .
          git commit -m "Add: page"
          echo "::endgroup::"
      
      - name: Publish
        run: |
          cd gh-pages
          git push -f origin gh-pages